# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FichiersAtelier2/atelier2.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2dvi_0_0/design_1_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_proc_ss_0_0 || ORIG_REF_NAME==design_1_v_proc_ss_0_0} -quiet] -quiet

# Block Designs: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b || ORIG_REF_NAME==bd_d92b} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_0/bd_d92b_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_smartconnect_0_0 || ORIG_REF_NAME==bd_d92b_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/bd_ec8a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_0/bd_ec8a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_1/bd_ec8a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_2/bd_ec8a_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_3/bd_ec8a_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_4/bd_ec8a_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_5/bd_ec8a_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_6/bd_ec8a_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_7/bd_ec8a_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_8/bd_ec8a_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_9/bd_ec8a_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_10/bd_ec8a_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_11/bd_ec8a_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_12/bd_ec8a_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_13/bd_ec8a_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_14/bd_ec8a_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_15/bd_ec8a_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_16/bd_ec8a_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_17/bd_ec8a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_18/bd_ec8a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_19/bd_ec8a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_20/bd_ec8a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_21/bd_ec8a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_22/bd_ec8a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_23/bd_ec8a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_24/bd_ec8a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_25/bd_ec8a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_26/bd_ec8a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_27/bd_ec8a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_28/bd_ec8a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_29/bd_ec8a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_30/bd_ec8a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_31/bd_ec8a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_32/bd_ec8a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_33/bd_ec8a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_34/bd_ec8a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_35/bd_ec8a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_36/bd_ec8a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_37/bd_ec8a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_38/bd_ec8a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_39/bd_ec8a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_40/bd_ec8a_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_41/bd_ec8a_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_42/bd_ec8a_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_43/bd_ec8a_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_44/bd_ec8a_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_45/bd_ec8a_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_46/bd_ec8a_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_1/bd_d92b_vsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_vsc_0 || ORIG_REF_NAME==bd_d92b_vsc_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_2/bd_d92b_hsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_hsc_0 || ORIG_REF_NAME==bd_d92b_hsc_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_3/bd_d92b_input_size_set_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_input_size_set_0 || ORIG_REF_NAME==bd_d92b_input_size_set_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_4/bd_d92b_rst_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_rst_axis_0 || ORIG_REF_NAME==bd_d92b_rst_axis_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_d92b_reset_sel_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_reset_sel_axis_0 || ORIG_REF_NAME==bd_d92b_reset_sel_axis_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_d92b_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_axis_register_slice_0_0 || ORIG_REF_NAME==bd_d92b_axis_register_slice_0_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_7/bd_d92b_axis_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_axis_fifo_0 || ORIG_REF_NAME==bd_d92b_axis_fifo_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_8/bd_d92b_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_xlslice_0_0 || ORIG_REF_NAME==bd_d92b_xlslice_0_0} -quiet] -quiet

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_9/bd_d92b_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_xlslice_1_0 || ORIG_REF_NAME==bd_d92b_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_testPatternGenerator_0_0/design_1_testPatternGenerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_testPatternGenerator_0_0 || ORIG_REF_NAME==design_1_testPatternGenerator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_myColorRegister_0_0/design_1_myColorRegister_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_myColorRegister_0_0 || ORIG_REF_NAME==design_1_myColorRegister_0_0} -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_1/bd_ec8a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_1/bd_ec8a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_2/bd_ec8a_arinsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_3/bd_ec8a_rinsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_4/bd_ec8a_awinsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_5/bd_ec8a_winsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_6/bd_ec8a_binsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_7/bd_ec8a_aroutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_8/bd_ec8a_routsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_9/bd_ec8a_awoutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_10/bd_ec8a_woutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_11/bd_ec8a_boutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_12/bd_ec8a_arni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_13/bd_ec8a_rni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_14/bd_ec8a_awni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_15/bd_ec8a_wni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_16/bd_ec8a_bni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_20/bd_ec8a_s00a2s_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_21/bd_ec8a_sarn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_22/bd_ec8a_srn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_23/bd_ec8a_sawn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_24/bd_ec8a_swn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_25/bd_ec8a_sbn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_26/bd_ec8a_m00s2a_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_27/bd_ec8a_m00arn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_28/bd_ec8a_m00rn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_29/bd_ec8a_m00awn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_30/bd_ec8a_m00wn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_31/bd_ec8a_m00bn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_33/bd_ec8a_m01s2a_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_34/bd_ec8a_m01arn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_35/bd_ec8a_m01rn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_36/bd_ec8a_m01awn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_37/bd_ec8a_m01wn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_38/bd_ec8a_m01bn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_40/bd_ec8a_m02s2a_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_41/bd_ec8a_m02arn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_42/bd_ec8a_m02rn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_43/bd_ec8a_m02awn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_44/bd_ec8a_m02wn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_1/ip/ip_45/bd_ec8a_m02bn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_0/ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_1/bd_d92b_vsc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_vsc_0 || ORIG_REF_NAME==bd_d92b_vsc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_2/bd_d92b_hsc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_hsc_0 || ORIG_REF_NAME==bd_d92b_hsc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_3/bd_d92b_input_size_set_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_4/bd_d92b_rst_axis_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_rst_axis_0 || ORIG_REF_NAME==bd_d92b_rst_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_4/bd_d92b_rst_axis_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_rst_axis_0 || ORIG_REF_NAME==bd_d92b_rst_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_d92b_reset_sel_axis_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_reset_sel_axis_0 || ORIG_REF_NAME==bd_d92b_reset_sel_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_d92b_reset_sel_axis_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_5/bd_d92b_reset_sel_axis_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_reset_sel_axis_0 || ORIG_REF_NAME==bd_d92b_reset_sel_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_6/bd_d92b_axis_register_slice_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_axis_register_slice_0_0 || ORIG_REF_NAME==bd_d92b_axis_register_slice_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_arinsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_rinsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_awinsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_winsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_binsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_aroutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_routsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_awoutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_woutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_boutsw_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_arni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_rni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_awni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_wni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_bni_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_s00a2s_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sarn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_srn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sawn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_swn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_sbn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00s2a_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00arn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00rn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00awn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00wn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00bn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m01s2a_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m01arn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m01rn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m01awn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m01wn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m01bn_0_ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: c:/Universite/S4/Projet/Atelier2/Atelier/Atelier.gen/sources_1/bd/design_1/design_1_ooc.xdc
